### ISSUE TITLE
Sometimes when user expands hamburger menu and attempts navigation to another tab, both previous and newly selected tabs are highlighted

### ISSUE THREAD

**Issue by teodoradima** [code4romania/stam-acasa#306] opened 2020-04-21 20:27 UTC
**Platform**: Mobile, Safari browser

Sometimes when user expands hamburger menu and attempts navigation to another tab, both previous and newly selected tabs are highlighted. However, new tab content is rendered successfully.

![image](https://user-images.githubusercontent.com/9938889/79910403-51d92e00-8427-11ea-9d80-11e5b6a12666.png)

**Comment by surdu** [comment] 2020-04-25 15:31
Couldn't reproduce on web and android 😞

**Comment by teodoradima** [comment] 2020-04-25 16:28
I can't reproduce it anymore on iOS as well. I guess we can close it?

**Comment by aniri** [comment] 2020-04-25 16:33
closing this for now as it can't be reproduced. maybe it was fixed indirectly :/

**Closed as completed by aniri** 2020-04-25 16:33 UTC
Labels: front-end, medium-priority
