### ISSUE TITLE
Missing mandatory field alert message for all open questions

### ISSUE THREAD

**Issue by DragomirStefanaCatalina** [code4romania/stam-acasa#313] opened 2020-04-22 09:07 UTC
Starting point: https://dev.stamacasa.ro/evaluation/me

**Expected**:
Mandatory fields to be completed with characters/digits when you answer positive to an open question

**Actual**:
The user can go forward by pressing space in the field to be completed & by clicking on

> Înainte

No mandatory field alert message

![Screenshot 2020-04-22 at 11 36 11](https://user-images.githubusercontent.com/61550276/79962031-335b4d00-8490-11ea-8f51-d7476cf8ff3e.png)

![Screenshot 2020-04-22 at 11 36 26](https://user-images.githubusercontent.com/61550276/79962056-40783c00-8490-11ea-9860-2715b387b4c3.png)

![Screenshot 2020-04-22 at 11 36 44](https://user-images.githubusercontent.com/61550276/79962179-6b629000-8490-11ea-9e7c-2f7c484542e5.png)

![Screenshot 2020-04-22 at 11 36 59](https://user-images.githubusercontent.com/61550276/79962225-75848e80-8490-11ea-8f3c-8860da6f6789.png)

![Screenshot 2020-04-22 at 11 37 24](https://user-images.githubusercontent.com/61550276/79962305-8d5c1280-8490-11ea-89dc-b54ff50b7552.png)

![Screenshot 2020-04-22 at 11 37 39](https://user-images.githubusercontent.com/61550276/79962340-951bb700-8490-11ea-98f8-db42ab5e7e73.png)

![Screenshot 2020-04-22 at 11 37 55](https://user-images.githubusercontent.com/61550276/79962380-a238a600-8490-11ea-8870-818161917d6c.png)

![Screenshot 2020-04-22 at 11 38 09](https://user-images.githubusercontent.com/61550276/79962402-a9f84a80-8490-11ea-89ca-f1ded0272277.png)

![Screenshot 2020-04-22 at 11 38 23](https://user-images.githubusercontent.com/61550276/79962447-b8defd00-8490-11ea-9957-45a4655e02c3.png)

![Screenshot 2020-04-22 at 11 38 38](https://user-images.githubusercontent.com/61550276/79962461-be3c4780-8490-11ea-8ee5-24f564df15f9.png)

![Screenshot 2020-04-22 at 11 32 58](https://user-images.githubusercontent.com/61550276/79962513-cc8a6380-8490-11ea-8c11-caf62e7ec3d0.png)

![Screenshot 2020-04-22 at 11 33 15](https://user-images.githubusercontent.com/61550276/79962529-d14f1780-8490-11ea-8033-571a2e65e9eb.png)

![Screenshot 2020-04-22 at 11 34 47](https://user-images.githubusercontent.com/61550276/79962603-ed52b900-8490-11ea-8e3b-d24dc1a05e5b.png)

![Screenshot 2020-04-22 at 11 35 06](https://user-images.githubusercontent.com/61550276/79962629-f479c700-8490-11ea-93f3-26ced35e25de.png)

![Screenshot 2020-04-22 at 11 35 28](https://user-images.githubusercontent.com/61550276/79962663-ffccf280-8490-11ea-8d49-41cf9dbd7846.png)

![Screenshot 2020-04-22 at 11 35 42](https://user-images.githubusercontent.com/61550276/79962675-03607980-8491-11ea-8aca-330be4592a27.png)

**Comment by mmircea16** [comment] 2020-04-24 10:54
I think this fixed in the latest version by the use of a datepicker library. Looking at: https://taskforce-fe-components.now.sh/?path=/story/form--with-date-pickers , I can't reproduce it.

**Comment by aniri** [comment] 2020-04-29 08:19
I confirm, this seems fixed in the latest version on https://dev.stamacasa.ro/ :smile: 

Closing the issue :)

**Closed as completed by aniri** 2020-04-29 08:19 UTC
Labels: help wanted, front-end
