### ISSUE TITLE
Cant reset your password 

### ISSUE THREAD

**Issue by DragomirStefanaCatalina** [code4romania/stam-acasa#259] opened 2020-04-18 19:17 UTC
Starting point: https://dev-is.stamacasa.ro/account/login?ReturnUrl=%2Fconnect%2Fauthorize%2Fcallback%3Fclient_id%3Dawsjsclient%26redirect_uri%3Dhttps%253A%252F%252Fdev.stamacasa.ro%252Fsignin-oidc%26response_type%3Did_token%2520token%26scope%3Dopenid%2520email%2520answersApi%2520usersApi%26state%3D4535c1bfedf2412ba11b7315ebd92ffe%26nonce%3D636eb371aec7490fb5198349ce9feb4f

**Expected**:
Forgot your password email reset 

**Actual**:
Click on 

> Ai uitat parola?

![Screenshot 2020-04-18 at 22 12 20](https://user-images.githubusercontent.com/61550276/79669136-1f7ac700-81c2-11ea-9574-da11a80025fc.png)

https://dev-is.stamacasa.ro/register blank page appears

**Comment by surdu** [comment] 2020-04-19 00:26
This is a duplicate of #237

**Closed as completed by surdu** 2020-04-19 00:26 UTC
